#!/bin/bash
set -ux

{% for gateway in gateways %}
ip link add dev wgBridge-{{gateway.port}} type wireguard
wg setconf wgBridge-{{gateway.port}} /etc/wireguard/wgBridge-{{gateway.port}}.conf
ip link set up wgBridge-{{gateway.port}}
{% endfor %}

ip link add dev wgInternal type wireguard
wg setconf wgInternal /etc/wireguard/wgInternal.conf
ip link set dev wgInternal mtu 1340
ip link set up wgInternal

# is this really any different/better than slapping it on eth0 and sharing routes?
{% for gateway in gateways %}
ip addr add {{exit_mesh_ip}} dev wgBridge-{{gateway.port}}
{% endfor %}
ip addr add {{internal_nat_ip}}/16 dev wgInternal || exit 0
