#!/bin/bash
set -ux

{% for gateway in gateways %}
ip link set down wgBridge-{{gateway.port}}
ip link del dev wgBridge-{{gateway.port}} type wireguard
{% endfor %}

ip link set down wgInternal
ip link del dev wgInternal type wireguard
