# Sets up an Althea exit node, which proxies traffic to the internet and bills for it

- name: Install Althea exit
  hosts: exit
  user: root
  serial: 1
  roles:
    - install-deps
    - install-babel
    - install-wireguard
    - { role: postgresql, when: standalone|bool }
    - install-rita-exit
    - security
    - logrotate
    - set-qdisc
    - { role: graylog, when: enterprise|bool }
