# Handle log growth

- name: Set log retention values for systemd
  command: "journalctl --vacuum-size=2G"
  become: true
  ignore_errors: true

- name: Template logrotate config
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf
  become: true

- name: Run logrotate now
  shell: "logrotate /etc/logrotate.conf"
  become: true

- name: Move logrotate from daily to hourly
  shell: "mv /etc/cron.daily/logrotate /etc/cron.hourly/"
  ignore_errors: true
