---
- name: Check for Babel binary
  local_action: stat path="{{playbook_dir}}/babeld"
  register: babeld_bin

- name: Babel bin not present, download latest release
  get_url:
    url: "{{babeld_bin_url}}"
    dest: "/usr/bin/babeld"
    mode: 0755
    force: true
  become: true
  when: not babeld_bin.stat.exists

- name: Copy over babled
  copy:
    src: "{{playbook_dir}}/babeld"
    dest: /usr/bin/babeld
    mode: 0755
  become: true
  when: babeld_bin.stat.exists

- name: Template babeld conf
  template:
    src: babeld.conf.j2
    dest: /etc/babeld.conf
  become: true

- name: Open Babeld port
  iptables:
    chain: INPUT
    destination_port: "{{babeld_port}}"
    protocol: "{{item[0]}}"
    ip_version: "{{item[1]}}"
    jump: ACCEPT
    ctstate: NEW
  become: true
  with_nested:
    - ["tcp", "udp"]
    - ["ipv4", "ipv6"]
  when: not container

- name: Fail on nonsystemd systems
  fail:
    msg: "No support for non systemd services, please add support for your init system!"
  when: "ansible_service_mgr != 'systemd'"

- include_tasks: systemd.yml
